services:
  admin:
    build: ./admin
    ports:
      - "5174:80"
    networks:
      - network
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - network

networks:
  network:
    driver: bridge